name: workshop
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=3.2.0
  - asn1crypto=1.2.0
  - attrs=19.2.0
  - backcall=0.1.0
  - bleach=3.1.0
  - branca=0.3.1
  - ca-certificates=2019.11.27
  - certifi=2019.11.28
  - cffi=1.13.0
  - chardet=3.0.4
  - cryptography=2.7
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - folium=0.10.0
  - geographiclib=1.50
  - geopy=1.20.0
  - geos=3.8.0
  - gettext=0.19.8.1
  - glib=2.56.2
  - icu=58.2
  - idna=2.8
  - ipykernel=5.1.2
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.15.1
  - jinja2=2.10.3
  - jpeg=9b
  - jsonschema=3.0.2
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_console=6.0.0
  - jupyter_core=4.6.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx
  - libcxxabi
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran
  - libiconv=1.15
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libsodium=1.0.16
  - llvm-openmp=9.0.0
  - markupsafe=1.1.1
  - mistune=0.8.4
  - nbconvert=5.6.0
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=6.0.1
  - numpy=1.17.2
  - openssl=1.1.1d
  - pandas=0.25.2
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.5.1
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.3.1
  - proj4=5.2.0
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.10
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pygments=2.4.2
  - pyopenssl=19.0.0
  - pyproj=1.9.6
  - pyqt=5.9.2
  - pyrsistent=0.15.4
  - pysocks=1.7.1
  - python=3.7.4
  - python-dateutil=2.8.0
  - pytz=2019.3
  - pyzmq=18.1.0
  - qt=5.9.7
  - qtconsole=4.5.5
  - readline=7.0
  - requests=2.22.0
  - send2trash=1.5.0
  - setuptools=41.4.0
  - shapely=1.6.4
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.30.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.8
  - toolz=0.10.0
  - tornado=6.0.3
  - traitlets=4.3.3
  - urllib3=1.25.6
  - vincent=0.4.4
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11
  - pip:
    - docker==4.1.0
    - escapism==1.0.0
    - geopandas==0.6.2
    - jupyter-repo2docker==0.10.0
    - python-json-logger==0.1.11
    - ruamel-yaml==0.16.6
    - ruamel-yaml-clib==0.2.0
    - semver==2.9.0
    - toml==0.10.0
    - websocket-client==0.57.0
